### PR TITLE
Cleaning up reference to TripleO

### PR DESCRIPTION
**Pull request by kajinamit**
This PR removes all the remaining references to TripleO.

### CODE REVIEW

**Comment by raukadah** [comment]
Thank you @kajinamit for working on this. The rdo team has not removed the tripleo component yet and reusable packages from tripleo component is not yet moved to podified component. that's why I would avoid merging it now.

**Comment by kajinamit** [comment]
> Thank you @kajinamit for working on this. The rdo team has not removed the tripleo component yet and reusable packages from tripleo component is not yet moved to podified component. that's why I would avoid merging it now.

Thanks for letting me know it. That makes sense.
Let me know if you want to merge some fixes earlier independently. For example we might want to merge fix for `roles/repo-setup/tasks/yum-config-compose-no-collections.yml` or renaming of some task files in case that affects CI workflow. If needed I can create a separate PR.

**Comment by raukadah** [comment]
> Thanks for letting me know it. That makes sense. Let me know if you want to merge some fixes earlier independently. For example we might want to merge fix for `roles/repo-setup/tasks/yum-config-compose-no-collections.yml` or renaming of some task files in case that affects CI workflow. If needed I can create a separate PR.

Sounds good to create a separate pr, thank you :-)

**Comment by kajinamit** [comment]
I'll create a different PR to address the remaining references.

**Pull request closed without merging**
